// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMIH1IqGq2ZVvgJ7EQQukgsmUEgGKODMc',
    appId: '1:606356496406:web:821ff2ba862d4867245537',
    messagingSenderId: '606356496406',
    projectId: 'burger-shop-9ebbd',
    authDomain: 'burger-shop-9ebbd.firebaseapp.com',
    storageBucket: 'burger-shop-9ebbd.firebasestorage.app',
    measurementId: 'G-9VQVBLCCGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUnXqRFyPPYZPwbaEo2PQTZngkCoOwUg4',
    appId: '1:606356496406:android:182a21754d979de3245537',
    messagingSenderId: '606356496406',
    projectId: 'burger-shop-9ebbd',
    storageBucket: 'burger-shop-9ebbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHkXMq_r6-O4ULLbq6Ixybf0K4QzFVDqo',
    appId: '1:606356496406:ios:7489b979928cde4c245537',
    messagingSenderId: '606356496406',
    projectId: 'burger-shop-9ebbd',
    storageBucket: 'burger-shop-9ebbd.firebasestorage.app',
    iosBundleId: 'com.example.burgerShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHkXMq_r6-O4ULLbq6Ixybf0K4QzFVDqo',
    appId: '1:606356496406:ios:7489b979928cde4c245537',
    messagingSenderId: '606356496406',
    projectId: 'burger-shop-9ebbd',
    storageBucket: 'burger-shop-9ebbd.firebasestorage.app',
    iosBundleId: 'com.example.burgerShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMIH1IqGq2ZVvgJ7EQQukgsmUEgGKODMc',
    appId: '1:606356496406:web:0a53694888b2ec31245537',
    messagingSenderId: '606356496406',
    projectId: 'burger-shop-9ebbd',
    authDomain: 'burger-shop-9ebbd.firebaseapp.com',
    storageBucket: 'burger-shop-9ebbd.firebasestorage.app',
    measurementId: 'G-2WRY77C50V',
  );
}
